target 'ReactNavigationSample' do
  # Uncomment the next line to define a global platform for your project
  # platform :ios, '9.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # AppAuth Pod
  # In production, just use `pod 'AppAuth'` without the path reference.
  pod 'AppAuth'

end
